### ISSUE TITLE
Unicode values outside Basic Multilingual Plane cannot be processed correctly.

### ISSUE THREAD

**Issue by lixiangliu** [nodebox/opentype.js#168]
For example:

`font.stringToGlyphs('\u{2f894}')` will return an array with two “.nodef” in it. 
<img width="419" alt="2015-12-12 21 26 42" src="https://cloud.githubusercontent.com/assets/10280733/11762111/0fcb0a76-a117-11e5-98a3-87f744a44504.png">

If `font.glyphs.glyphs[...]` is being used to access a certain glyph directly, then it will return an object with an undefined unicode value. 
<img width="527" alt="2015-12-12 21 26 59" src="https://cloud.githubusercontent.com/assets/10280733/11762112/1e584752-a117-11e5-9bfb-8dd1495fbcda.png">

**Comment by lixiangliu** [comment]
It seems this is the limitation of cmap format, since format 4 only supports 16-bit unicode value.

**Comment by fdb** [comment]
Would it help if we parsed a different cmap format?

**Comment by lixiangliu** [comment]
In that case, cmap format 12 is probably a good choice then, it’s widely adopted and the superset of format 4.

**Comment by Jolg42** [comment]
@lixiangliu cmap 12 read support was just added with PR #207 😉

**Comment by fdb** [comment]
Closing this issue because of the cmap 12 support. @lixiangliu  let me know if there's something else that blocks you from working wit these fonts.

**Comment by amart1n** [comment]
The same issue still exists with values outside the BMP. Looks like it may be because of the limitations of `charCodeAt()` https://mathiasbynens.be/notes/javascript-unicode#code-point-from-string

**Comment by Jolg42** [comment]
@amart1n You're right `charCodeAt()` "will always return a value that is less than 65536." ([ref](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/charCodeAt))

[codePointAt()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/codePointAt) is the new method to use but because of the compatibility we would need to add Mathias's polyfill: https://github.com/mathiasbynens/String.prototype.codePointAt and use it instead of `charCodeAt()` to have a full Unicode support.

**Comment by fpirsch** [comment]
Closed through #338
