### ISSUE TITLE
Using local fonts

### ISSUE THREAD

**Issue by BruceSherwood** [nodebox/opentype.js#209]
Aided by Kadir Haldenbilen, I have used opentype.js to read glyph contours and display 3D text in WebGL. Here's an example:

http://www.glowscript.org/#/user/GlowScriptDemos/folder/Examples/program/BillboardingText

I include in the GlowScript library copies of the fonts Robot-Medium.ttf and NimbusRomNo9L-Med.otf, which are sent over the web to the browser. It would make more sense to read (say) Verdan, Times New Roman, and Courier New from the local computer, without having to send them from the server. Is there a way to reference a local font from opentype.js? I didn't see anything about this.

A separate question is whether you know of a widely used/available font that includes Chinese and other important Asian fonts?

Here's what I've posted in the key GlowScript file, extrude.js:

// Font machinery by Kadir Haldenbilen, June 2016
// Adapted by Bruce Sherwood for use in GlowScript
// Tessellation with multiple holes, JavaScript version: https://github.com/r3mi/poly2tri.js
// For explanation of poly2tri, see http://sites-final.uclouvain.be/mema/Poly2Tri
// Font manipulation: https://github.com/nodebox/opentype.js
// Public-domain sans serif font Roboto-Medium.ttf from http://www.1001freefonts.com/roboto.font
// Public-domain serif font NimbusRomNo9L-Med.otf from http://www.1001fonts.com/nimbus-roman-no9-l-font.html
// These fonts were chosen both for appearance and complete coverage (tested for Greek, Russian, Esperanto).

**Comment by fpirsch** [comment]
Hi @BruceSherwood ,
for security reasons, the browser does not let scripts know which fonts are installed locally, nor which fonts it actually uses on the page. The CSS or canvas font-family is just a hint.
For the same reason, scripts are not allowed to read local files.

**Comment by BruceSherwood** [comment]
Thanks much for the explanation. Do you happen to know anything about the Chinese situation? The only font I've run across that has Chinese is MS-Gothic.

**Comment by fpirsch** [comment]
https://en.wikipedia.org/wiki/List_of_CJK_fonts
Windows is shipped with the JhengHei (traditional Chinese) and YaHei (simplified Chinese) fonts.

**Comment by BruceSherwood** [comment]
Thanks for the tip.

**Comment by thekingofcity** [comment]
For those who are curious about widely used/available East Asian (Chinese, Japanese, Korean) fonts, [Google's Noto Sans CJK](https://fonts.google.com/noto/use) should be on the list. They are free and don't require any license for commercial use.

However, do keep in mind that some Unicode characters should display differently based on different languages/official requirements in that country. E.g. Even if the following 草 is the same word in different languages, it has different _official_ visual expressions or glyphs.

![image](https://github.com/opentypejs/opentype.js/assets/3353040/f79fec68-4b56-4b94-aa89-e3f89216d5ae)

> See the difference at the top of each character. From left to right are Chinese(PRC) Chinese(Hong Kong SAR) Chinese(ROC) Japanese Korean Vietnamese.

For the full difference see here: https://www.unicode.org/charts/PDF/U4E00.pdf

The best practice is to only use the right font for one language/country and prepare a different one for another. DO NOT use the one that just works(could display the character but is not intended for that language and is displayed just because the character exists in this language).
