### ISSUE TITLE
Can't create coverage table format 2 yet.

### ISSUE THREAD

**Issue by dennisfrostlander** [nodebox/opentype.js#223]
Starting from 0.6.5 release, there is now an error when parsing OpenSans-Reulgar.ttf.
Can't create coverage table format 2 yet.

See the fiddle for an example. Version 0.6.4 works fine on the same font file.
https://jsfiddle.net/vd48vyzf/

**Comment by fpirsch** [comment]
Strange. I'll take a look at this. Thanks for the info.

**Comment by fpirsch** [comment]
The error is not during the parsing, which runs fine.
It occurs in the `toArrayBuffer` method, which prepares writing. And Opentype cannot currently write only simple fonts.
Basically, what your example is doing is:
  * parsing the original font
  * writing back to an array buffer, which throws an error because the font is too complex
  * trying to parse the result, which doesn't happen because of the previous error

What the previous version (0.6.4) did, without throwing an error:
  * parse the original font
  * write back to an array buffer, loosing vast amounts of information because the font is so complex
  * parse the array buffer, retrieving only a small fraction of the original font

If you really want this to work, you can add this line just before the `toArrayBuffer` line:
    `delete font.tables.gsub;`

**Comment by dennisfrostlander** [comment]
Thanks for the explanation and the workaround. You mentioned a couple of times that OpenSans is too complex. This is just the standard ttf file from google fonts github repo, and OpenSans is one of the most popular fonts out there. Is there any better way to handle such font with opentype.js? Maybe some preprocessing step to get rid of information that opentype cannot parse anyway?
I am parsing the font to determine the width/height of different pieces of text without using canvas.

**Comment by fpirsch** [comment]
OpenSans is too complex **now** for opentype.js to **write/edit/modify**, but **reading/extracting information** is done very well.
What you need in your callback is probably to call `font.getPath`, or use the `font.tables` object to retrieve metrics.
There is absolutely no reason to call `toArrayBuffer` and parse again.

**Comment by dennisfrostlander** [comment]
Thanks, I was also using the same buffer to embed the font in css via data-url, but I can workaround that by loading with a regular url.
Thanks a lot for the tips. Regarding this issue, feel free to close it unless you want to restore original behavior or document the workaround.

**Comment by fpirsch** [comment]
Well, the font writing feature is still young and pretty basic, I guess we'll have to document that fact ;-)

**Comment by halmos** [comment]
Any new updates on supporting more advanced gsub tables?

**Comment by nestarz** [comment]
Is there a workaround ?

**Comment by bugeats** [comment]
/me wishing there was a write-mode that **just worked** and logged warnings for any unsupported features that were dropped.

**Comment by Connum** [comment]
I just created PR #450 which fixes this issue. Testing of my branch https://github.com/Connum/opentype.js/tree/implement-writing-coverage-table-format-2 is encouraged.
