### ISSUE TITLE
Parsing the getPath object

### ISSUE THREAD

**Issue by iceblu3710** [nodebox/opentype.js#248]
`path = font.getPath('Hello, World!', 10, 10, 100 );` will output an object:

```javascript
path {
commands: Array[180],
fill: "black",
stroke: null,
strokeWidth: 1
}: object
```

Inside the commands are the glyphs:
```javascript
[0]:
  type: "M",
  x: 18,
  y: 10,
[13]:
  type: "Z"
```

I had assumed that if there was no `x, y` coords that it means this was a space. However I was very wrong. How the heck do I translate the path output?

I need to close the path of each individual letter by referencing the letters first coordinate but have no idea where each letter ends.

**Comment by iceblu3710** [comment]
I just figured out what the types are for. M = Start of letter, L = Letter segment, Z = End of letter. And all the y coords are inverter.

**Comment by fdb** [comment]
OpenType.js just uses the [SVG path data format](https://www.w3.org/TR/SVG/paths.html#PathData).

**Comment by fdb** [comment]
Oh and the coordinates are inverted because they are stored that way (in PostScript format).

For reference: 
- M = Moveto: takes two arguments x, y.
- L = Lineto: takes two arguments x, y.
- Q = Quadto: quadratic curve. Takes four arguments: x1, y1, x, y.
- C = Curveto: Bézier curve. Takes six arguments: x1, y1, x2, y2, x, y.
- Z = Close: closes the subpath.
