### ISSUE TITLE
conditional contours in glyph pairs

### ISSUE THREAD

**Issue by danmarshall** [nodebox/opentype.js#285]
Hello, I bet there is a name for this in the font world, I just don't know what you call it.

![image](https://cloud.githubusercontent.com/assets/11507384/25408701/c2b7bc98-29c3-11e7-8dd4-65f975b6e86c.png)

If you look at https://fonts.google.com/specimen/Vibur there is an easy way to see the phenomenon.
The 'r' glyph has an extra bar on the left, only when it follows another letter.

Does opentype.js support this? In my code, I am not able to get the connecting part of the 'r' glyph, with the Vibur font.

**Comment by fdb** [comment]
This is based on the [liga](http://ilovetypography.com/OpenType/opentype-features.html) OpenType feature of the font. It substitutes a sequence of glyphs with a new glyph. 

![screen shot 2017-04-26 at 11 37 49](https://cloud.githubusercontent.com/assets/8477/25428036/c36ab184-2a74-11e7-8783-a3f0d1618e13.png)
(Screenshot from the Glyphs app)

Although we have support for the `liga` feature, it seems it doesn't work in this font. I'll try to figure out why. 

/cc @fpirsch (he wrote the implementation)

**Comment by axkibe** [comment]
These ligatures may not be enabled in options.script='DFLT'; (that is options.script unset)
Try with options.script = 'latn';

PS: script of the options object should be documented and the demo may have a select box for language setting, when ligatures are enabled.

**Comment by fdb** [comment]
Ha! You helped me find a bug in the ligature code. Turns out the `expandCoverage` function, which figures out which glyphs the ligature substitution applies to, has [this snippet](https://github.com/nodebox/opentype.js/blob/220f784f003b6807c6ce122aa509b893c1e75a97/src/layout.js#L268):

```javascript
var ranges = coverageTable.ranges;
for (var i = 0; i < ranges; i++) {
    var range = ranges[i];
```
See the bug? The loop should use `ranges.length`, not `ranges`. After changing this, ligature substitution for Vibur works!

I'll make another release in a bit.
