### ISSUE TITLE
Canvas rendering: Hinting and subpixel antialiasing

### ISSUE THREAD

**Issue by Cryza** [nodebox/opentype.js#345]
Hello people!

Thanks for your work on this repository! It comes in really helpful for us working on a WebGL renderer for our our project over at https://github.com/onivim/oni

We would however love to keep the same rendering quality and legibility that we currently get from chrome even after the switch to opentype.js. For that purpose, I just tried out a few settings on https://opentype.js.org/ (great showcase!) and found out that the setup there does not perform hinting nor subpixel antialiasing. Unfortunately, both features are rather important for our code editor. After all, the code is what people are working on in our application :)

Now I have two questions I would like to ask:

1. Is it possible to somehow activate subpixel antialiasing and hinting while rendering to a canvas? (I only found #101 so far but there was no result in it and the issue is also 3 years old)
2. If it's not supported at the moment, would you accept PRs in the direction of adding these features? I would like to help with that in case you are interested, but I would probably need some help.

Thanks for your time!
## Context
The main reason why we're looking into replacing the chrome text shaping that we use within electron is the fact that our WebGL pipeline currently renders characters instead of glyphs, thus only supporting those glyphs that map 1:1 to a unicode code point. With fonts like FiraCode around, we would love to support advanced OpenType features like ligatures or contextual alternates, which is fortunately possible using fontkit!

## Your Environment
* Version used: 0.8.0
* Font used: FiraCode-Regular.otf
* Browser Name and version: Firefox 61
* Operating System and version (desktop or mobile): Windows 7 desktop
* Link to your project: https://github.com/onivim/oni

**Comment by axkibe** [comment]
opentype.js does have an engine for true type fonts hinting instructions. (I implemented it due to personal need). it doesn't for open type fonts, because those are completely different beast, or some (lower quality) true type fonts don't have hinting instructions, and rely on an auto hinter, that become more popular (opentype.js doesn't have an auto hinter)

Regarding subpixel rendering, that would up the canvas implementation of the browser. The last time I checked none of them did that. Theoretically it would be possible to render in an canvas 3 times as wide and use the pixel API to reduce that to RGB values, to achieve that 3 times effective horizontal resolution thingy. There are some demonstrations of this online, but they are more than slow. With WebGL it should be possible to offload this to a shader. I've not yet seen it done, nor did find the time to try do that.

**Comment by Cryza** [comment]
Thanks for your quick response, @axkibe!

With the insights you added, it almost looks like we will need to go for an established solution like freetype or even HarfBuzz to avoid regressions in rendering quality. I hope we will find another way :/

> Regarding subpixel rendering

I know for a fact that at least Chrome does perform subpixel-antialiased font rendering, also known as ClearType on Windows, if the canvas is set to be fully opaque. This is also working pretty nicely for us already in Oni, with the limitation that we can't support ligatures or advanced OpenType features as of now.
In any case, the text shaping engine has do perform some additional work if it should do subpixel antialiasing, and apparently opentype.js does not yet do that.

**Comment by axkibe** [comment]
Well it does do subpixel font rendering, because it is done by cleartype. However, a canvas also could do subpixel rendering when drawing a line... it didn't do that by itself the last time a checked. But a diagonal also looks more awesome when it does that.

Since opentype.js outputs vectors, it would need to rely on a vector rasterization engine to do subpixel rendering. It is possible to make a rasterization engine in javascript or use that "draw it on a 3 times bigger canvas and then just copy the RGB value of every 3rd pixel trick" but these are extremly slow.

As said, with WebGL I suppose this trick could be offloaded to the GPU or at least to a more native compiled version, since the shader is always compiled. But the last time I looked I've not seen anybody doing that. But this a year or two ago...

**Comment by axkibe** [comment]
PS: Also there is no way in javascript to know of the RGB pixel properties of the screen, so even if done, it's always a dirty hack a user would have to configure it's RGB display properties for you application somewhere.

With mobile devices, you would have different pixel setup if the device is held rotated or not. Which would also been taken in account.

Or for example, you'd have to turn of subpixel rendering, if for example a screen is mirrored on a beamer with a different RGB pixel layout. All things abstracted away from a html/javascript implentation on purpose.

The proper way would be for the browser to interact with the operating system to figure out RGB pixel layouts of attached screens, multi screen setups, etc. and turn on subpixel rendering for all things in the canvas (meaning drawing lines too, what opentype.js effectively does at the end). The last time a checked, no canvas implementation does that (yet)

**Comment by Jolg42** [comment]
@axkibe Indeed! About about auto hinting there is [ttfautohint](https://www.freetype.org/ttfautohint/) used by [Fontforge](https://fontforge.github.io/en-US/documentation/interface/hinting/) for example.

**Comment by axkibe** [comment]
interesting but ttfautohint is GPL or TTF licensed (3 clause bsd style) thus would complicate opentype.js licensing when imported a verbatim translated code. Not that I got time to do that anyway. I'm settled with TTF hinting. Similar issue with post script hinting, adobe has gifted libfreetype with a ps-font hinter, but it's GPL.
